version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: 
          name: Output hello world
          command: echo "hello world" > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - /*
  
  print_output_file:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: ~
      - run: 
          name: step to print output file
          command: |
            ls ~
            cat ~/output.txt

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires: 
            - save_hello_world_output

