version: 2.1

jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: 
          name: Output hello world
          command: |
            touch output.txt
            echo "hello world" > output.txt
            cat output.txt
            pwd

workflows:
  my_workflow:
    jobs:
      - build
